### ISSUE TITLE
Scroll bar missing in countries list

### ISSUE THREAD

**Issue by bushman413** [HomeITAdmin/nextcloud_geoblocker#1]
Using Chromium based browsers, the scroll bar in the countries list is not visible or usable/enabled.

When using Edge, the scroll bar momentarily appears until the list is fully loaded, at which point the scroll bar disappears.

Internet Explorer works like a charm though!

GeoBlocker 0.0.1
Nextcloud 17.0.1

Tested with Brave, Edge Chromium, Google Chrome, Edge, and successfully with Internet Explorer.

**Comment by HomeITAdmin** [comment]
Thanks for testing and giving feedback.
I only checked with Firefox so far where it is working correctly. Wouldn't have thought a simple select html tag can cause such problems in different browsers.

I can confirm that I could reproduce the problem with Chromium and Edge. 
In Firefox it is working fine. In Internet Explorer the Scrollbar is visible. 

In Internet Explorer, Chromium and Edge there is an additional problem, that not the content of the option tag is shown but the label field. Maybe the problem is connected.

I have to further investigate this to find the solution.

**Comment by HomeITAdmin** [comment]
With the help of the community I think I found the problem and fixed the style sheet.
I confirmed the fix with Chromium, Firefox and Konquerer. I prepare a bugfix release.
