### ISSUE TITLE
l10n: NOT_SHOWN_IN_LOG

### ISSUE THREAD

**Issue by Valdnet** [HomeITAdmin/nextcloud_geoblocker#38]
In Transefix there is the string `NOT_SHOWN_IN_LOG` to translate. In my opinion, the code needs to be corrected so that this value does not appear in the translation for translators.

https://github.com/HomeITAdmin/nextcloud_geoblocker/blob/93650bf24c74160f078b1c83c6edade4f89153be/lib/GeoBlocker/GeoBlocker.php#L53-L58

**Comment by Valdnet** [comment]
@HomeITAdmin ping.

**Comment by HomeITAdmin** [comment]
It is part of the error logging strings. I guess you could argue about if it makes sense to translate logging information. (Thinking about it, the user is not logged in at that moment, so what language is used anyhow. Is there a default language in Nextcloud? It should be the language of the server admin, because she must be able to read it. Ok, that is another topic... ;-) )

So to make it short, I thought it should be in the same language as the rest of the logging entry. Would it be better for translation to leave the "_" out or are the capital letters also a problem?

**Comment by Valdnet** [comment]
I think this text string shouldn't be in Transefix.

**Comment by HomeITAdmin** [comment]
Ok, I think it makes more sense to not translate log entries for the moment.
