### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Valdnet** [HomeITAdmin/nextcloud_geoblocker#7]
While trying to enter the app settings, a server error appears.

> Internal Server Error
> 
> The server was unable to complete your request.
> 
> If this happens again, please send the technical details below to the server administrator.
> 
> More details can be found in the server log.
> Technical details
> 
>     Remote Address: xxx.xxx.xx.xx
>     Request ID: Xjp-wDapCklkCIrM7TDntwAAACA

Steps:

1. Install the app.
2. Enter the Nextcloud administrator settings.
3. Choose GeoBlocked.

Error log:
```
[index] Error: Exception: Return value of OCA\GeoBlocker\LocalizationServices\GeoIPLookupCmdWrapper::geoiplookup() must be of the type string, null returned at <<closure>>

0. /home/xxx/public_html/chmura/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\Cont ... {}, "index")
1. /home/xxx/public_html/chmura/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OC\\Settings\\C ... r", "index", OC\AppFramework\ ... {}, {section: "geobl ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({section: "geobl ... "})
3. /home/xxx/public_html/chmura/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {section: "geobl ... "})
4. /home/xxx/public_html/chmura/lib/base.php line 1000
   OC\Route\Router->match("/settings/admin/geoblocker")
5. /home/xxx/public_html/chmura/index.php line 42
   OC::handleRequest()

GET /index.php/settings/admin/geoblocker
from xx.xxx.xx.xx by xxx at 2020-02-05T08:39:02+00:00

[PHP] Error: exec() has been disabled for security reasons at /home/xxx/public_html/chmura/apps/geoblocker/lib/LocalizationServices/GeoIPLookupCmdWrapper.php#9
```

App:
Nextcloud 17.0.0
GeoBlocker 0.0.2

**Comment by HomeITAdmin** [comment]
Thanks for these good error logs.

So it is clear what is happening. The app tries to use the "exec()" function to call the local program "geoiplookup", but this is prohibited by the php configuration in the php.ini

So, first of all, this should not lead to a crash. This is easy to fix.

But still then calling the location service is not working, because this configuration usually tries to prevent exactly what is needed here: calling another program on the server. So i guess it also does not make sense to use any other php function, because all will be disabled.

So if you cannot enable the use of the exec() function, then you cannot use this app at the moment. In some future release it is planned to add web services that can be used as location service.
