### ISSUE TITLE
ERROR: Database is not valid

### ISSUE THREAD

**Issue by pinkfloydFR** [HomeITAdmin/nextcloud_geoblocker#80]
Hi, 

trying to configure the geoblocker, but without success.

geoipupdate is working.

**I have :** 
```
root@nextcloud:/var/www/nextcloud/apps/geoblocker/3rdparty/maxmind_geolite2#
-rw-r--r-- 1 www-data www-data  366335 Jul 13 12:47 geoip2.phar
-rw-r--r-- 1 www-data www-data 4234782 Jul 13 13:03 GeoLite2-Country.mmdb
```

**and**

```
root@nextcloud:/usr/share/GeoIP# 
-rw-rw-rw-    1 www-data www-data  366335 Jul 13 12:49 geoip2.phar
-rw-------    1 root     root           0 Jul 13 12:51 .geoipupdate.lock
-rw-r--r--    1 www-data www-data 4234782 Jul 13 12:51 GeoLite2-Country.mmdb
```

**In the application :** 

![image](https://user-images.githubusercontent.com/49475899/125441974-a31275e2-817d-457c-83e8-c9c77c6c8495.png)

**when test with the php command i have :** 

```
php > include 'geoip2.phar'; use GeoIp2\Database\Reader; $reader = new Reader('/usr/share/GeoIP/GeoLite2-Country.mmdb'); print($reader->country('24.165.23.67')->country->isoCode);

PHP Parse error:  syntax error, unexpected 'include' (T_INCLUDE) in php shell code on line 2`
```

No more idea.... what i am doing wrong ? Thanks

**Comment by HomeITAdmin** [comment]
Can you try "/usr/share/GeoIP/GeoLite2-Country.mmdb" as the database location? 
It needs to be the full path including the filename.

Why the test with the php command is failing this way, I do not understand. In your Nextcloud this is working, because the check if the reader class exists is done before the check, if the database exists. So you would get a different error message if that would be a problem there too.

**Comment by pinkfloydFR** [comment]
Changing path with "/usr/share/GeoIP/GeoLite2-Country.mmdb"

"MaxMind GeoLite2": ERROR: Database is not valid, does not have the correct access rights or is not placed at /usr/share/GeoIP/GeoLite2-Country.mmdb.

Date de la base de données :
Impossible de déterminer la date de la base de données.


It's worst because the date of database is unknown now.

**Comment by HomeITAdmin** [comment]
If you only give the folder, then it is showing the date of the folder.
But for the service to work it must be the database file. 

The file size is reasonable, so I also guess, that it is valid.
The best guess is, that there is still something blocking the access. Maybe SELinux or AppArmor?

Can you try "/var/www/nextcloud/apps/geoblocker/3rdparty/maxmind_geolite2/GeoLite2-Country.mmdb", making sure, that the file is still there as shown in your first post.

**Comment by pinkfloydFR** [comment]
You got it ! 

with the path "/var/www/nextcloud/apps/geoblocker/3rdparty/maxmind_geolite2/GeoLite2-Country.mmdb" it's working !

Thanks for the help ! Appreciated.

**Comment by AChurba** [comment]
using apt and Installing on Ubuntu 20.04.02, the default MaxMind installation location is /usr/share/GeoIP.

add-apt-repository ppa:maxmind/ppa
apt-get update && apt-get install geoipupdate
nano /etc/GeoIP.conf
fill in the account details and save
geoipupdate -v
ls -la /usr/share/GeoIP
cd /usr/share/GeoIP
wget https://github.com/maxmind/GeoIP2-php/releases/download/v2.11.0/geoip2.phar

What has been necessary is to copy the geoip2.phar & GeoLite2-Country.mmdb to the nextcloud path
....nextcloud/apps/geoblocker/3rdparty/maxmind_geolite2
Take notice of the file ownership and set accordingly to your web user and web group (chown)
Then explicitly setting the location of the database to the above path and GeoLite2-Country.mmdb in the nextcloud GeoBlocker UI.

Since this is just a workaround, it will not satisfy update resilience. 

Please look into the root cause of the issue.

Thanks.

**Comment by HomeITAdmin** [comment]
Is it possible that you have Apparmor active (which seems to be the default in Ubuntu)?
So my best guess is, that Apparmor is preventing the access of the Web Server to folders outside the standard folder in your configuration. Can you check this?

**Comment by HomeITAdmin** [comment]
@AChurba could you verify the theory?

**Comment by HomeITAdmin** [comment]
Closing stale issue.
