### ISSUE TITLE
Choose the selection mode never stays

### ISSUE THREAD

**Issue by andyxheli** [HomeITAdmin/nextcloud_geoblocker#81]
Hello this issue just came up never had this issue before. Please see the video attached  Nextcloud 21.0.3 

Geoblocker 0.5.1

**Comment by andyxheli** [comment]
@HomeITAdmin Just wanted to let you know i downgraded to Version 0.5.0 and no issues the settings stay.

**Comment by HomeITAdmin** [comment]
Hmm, I have no idea how this can happen.

Between 0.5.0 and 0.5.1 are only very small differences:
- Translations update
- Small RIRData change for NC22 compatibility
- Activation of NC22

Nothing that has to do with the country selection. 
The values are stored in the app config table. Maybe there were some kind of problem with the database? Do you have any entries in the log at that time?

My best guess would be, that whatever the problem was, it is gone now. Could you update to 0.5.1 again and see, if it comes back?

**Comment by andyxheli** [comment]
Let me update and let you know what happens

**Comment by andyxheli** [comment]
Looks good. Very strange. Thanks for your help.

**Comment by andyxheli** [comment]
@HomeITAdmin I though it worked but nope still the same issue when you try to change it the change dosent stay

**Comment by andyxheli** [comment]
It only happens on MacOS not windows I tried different browsers and still the same issue on the Mac strange
